### ISSUE TITLE
Client Allocation Request for: Nonentropy JP

### ISSUE THREAD

**Issue by NonentropyJP** [filecoin-project/filecoin-plus-client-onboarding#2276] opened 2022-08-03 12:55 UTC
---

# Client Allocation Questions 

## Core Information
- Name: Nonentropy JP
- Website / Social Media: https://nonentropy.jp
- Region: Asia (excl. Greater China)
- DataCap Requested: 1.5TiB
- Addresses to be Notarized: f1zuidelrq2lfunc3zha3me4k3v62o7af2gxfymti
- Notary Requested: @MasaakiNawatani

@NonentropyJP Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment] 2022-08-04 02:09
Hi, I believe your organization applied for datacap from me the other day and I have granted it. Thanks!

**Comment by NonentropyJP** [comment] 2022-08-04 02:17
Greetings @MasaakiNawatani yes we applied but we made a mistake in the datacap amount we require. We wish to modify our request. thank you.

**Comment by MasaakiNawatani** [comment] 2022-08-10 02:10
Closing this issue. This is a duplicate of #2300

**Closed by MasaakiNawatani** 2022-08-10 02:10 UTC
