### ISSUE TITLE
Client Allocation Request for: ShhHuiYa

### ISSUE THREAD

**Issue by HUIYA233** [filecoin-project/filecoin-plus-client-onboarding#608] opened 2021-08-03 12:58 UTC
---

# Client Allocation Questions 

## Core Information
- Name: ShhHuiYa
- Website / Social Media: http://www.shhuiya.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1eq723qfqsnko7fectlqerdxegj7wxrkouc2bloy
- Notary Requested: MRJAVAZHAO

@HUIYA233 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dkkapur** [comment] 2021-08-03 22:33
@MRJAVAZHAO need you to accept access to the repo so we can assign this to you!

**Comment by MRJAVAZHAO** [comment] 2021-08-04 02:44
@dkkapur OK. I will check it later.

**Comment by MRJAVAZHAO** [comment] 2021-08-04 02:49
@HUIYA233 
I'm very happy to receive your application. If you have any question, you can contact me on the slack, my account is @binghe Lab(冰河分布式存储实验室).
There are some questions and hope to get your reply.

Please provide organization name, the employee, business scale, social media accounts&follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email); If there is any legal risk exist, please give the percentage of the responsibility belongs to you.
When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?
Please describe your business data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.
In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.
Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by HUIYA233** [comment] 2021-08-04 12:24
Dear,MRJAVAZHAO 

Organization name: Shanghai Huia Information Technology Co.
The employee: Around 50
Business scale: Serving the whole country
Social media accounts&follwers: Wechat official account:上海汇亚; Followers: around 500.
Business license: It has been sent via email.

When did you start learning about Filecoin: 2020; We learned about it through some friends.
Our Projects：
Shanghai Huia Information Technology Co is a double-soft enterprise qualified by Shanghai Information Commission and Economic Commission.  It is a leading e-commerce operation service provider in Shanghai. The company is committed to providing traditional enterprises with special services such as interconnection diagnosis, consulting, WeChat public platform access, WeChat mall construction, product photography, visual design, event planning, WeChat promotion, etc. We have successfully helped more than 100 traditional merchants to realize WeChat marketing.

In order to adapt to the development of the times, we have been investing in research and development of the latest technology.Filecoin is a typical representative of blockchain technology application. And still in the early stages, we think Filecoin has great potential.We want to use Filecoin as the underlying technology to provide our customers with a more secure and affordable storage service.

What do you want to get from Filecoin?
Fileccoin is a potential application and we want to try to see if we can commercialize it.

Any suggestions or expectations for the Filecoin Network?
None.

Business data volume:30TiB in total, 5TiB for this time.
Source: Business Data.
Type and format:Mainly video and packaging files (Data for system testing)
Publicity of the data to be stored in Filecoin: It is publicly available,Public retrieval is possible when the Filecoin network supports retrieval

In which area do you plan to store you data? 
China Mainland.

How many miners do you want to find ? 
3-4miners

Please list the miner ID.
Not sure.

How about the proportion of the storage for each miner? 
We prefer to distribute equally

What are the requirements about miners? 
We tend to choose miners with good credit and sufficient scale
Redundancy plan: 3 copies of data.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.
Yes,we are willing to disclose transaction information here.


Looking forward to hearing from you!

**Comment by MRJAVAZHAO** [comment] 2021-08-05 08:42
@HUIYA233 I do not find your email, can you check it again, my email address: service@athenapool.com.

**Comment by MRJAVAZHAO** [comment] 2021-08-05 08:48
> Publicity of the data to be stored in Filecoin: It is publicly available,Public retrieval is possible when the Filecoin network supports retrieval
Is there any internet search tools or websites available?

**Comment by HUIYA233** [comment] 2021-08-05 11:43
Okay, I've sent it to this email address.

I transferred some of my files to the cloud,anyone on the internet with this link can view.
https://drive.google.com/drive/folders/1sQ7Jq6y8abt0VOGyQUQANR-QuwCM270a?usp=sharing

**Comment by MRJAVAZHAO** [comment] 2021-08-06 02:17
Thanks for your cooperation.
We are very concerned about the reputation of a company. After verification, it is found that your company has many legal disputes. We hope you can give a detailed description, such as the cause, the result and the attribution of the responsibility.

**Comment by HUIYA233** [comment] 2021-08-06 03:02
Thanks for your concern.

We are a functioning company.The legal dispute you mentioned.

The main issue is about the change of business address and tax transfer. 2015 due to the expansion of our business we need to move to other regions, and then the tax transfer issue occurred. Now we have solved it, after all, it happened in 2015

Others are mainly business disputes with customers,I think this is your main concern.As an Internet technology service provider established for many years and serving many customers,Small-scale legal disputes are inevitable.Since our establishment, we have had legal disputes with only 2 clients.And this happened in 2014 and 2016,It has all been solved so far

We are allowed by law to disclose the outcome of one of these trials.
![WechatIMG155](https://user-images.githubusercontent.com/88384792/128449735-23123c6b-8fd7-4584-bab3-cb379f2c2b6e.jpeg)



I hope this clears up any doubts you may have had, thank you very much!

**Comment by MRJAVAZHAO** [comment] 2021-08-10 02:38
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebf2dfxwilocqyugjm3eik5mdy7loswxj2i3ownfi5ztzjlx6lnes 
#### Address 
> f1eq723qfqsnko7fectlqerdxegj7wxrkouc2bloy
#### Datacap Allocated
> 1TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebf2dfxwilocqyugjm3eik5mdy7loswxj2i3ownfi5ztzjlx6lnes

**Closed by MRJAVAZHAO** 2021-08-10 02:38 UTC
Labels: state:Granted

**Comment by MRJAVAZHAO** [comment] 2021-08-10 03:01
@HUIYA233 We allocated 1TiB at first application.
You can re-apply when DataCap has been used up.
Hope you have a good experience in the Filecoin network.
If you have any problem, you can contact me any time.
