### ISSUE TITLE
Client Allocation Request for: IPFS Found

### ISSUE THREAD

**Issue by IPFSUnion** [filecoin-project/filecoin-plus-client-onboarding#194] opened 2021-02-22 09:20 UTC
---

# Client Allocation Questions 

## Core Information
- Name: IPFS Found
- Website / Social Media: https://filecoin.in/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1jwiwiqfskfeiim5jrpjy65atp3ytzg4swpcijpi
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment] 2021-02-25 09:59
Duplicate of #https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/10

**Closed by ozhtdong** 2021-02-25 09:59 UTC
Labels: bot:lookingGood, region:Greater China, state:Verifying
